import pytest

from pera_panel.lua_settings import read_mods
from pera_panel.storage import PanelError, lua


def test_common_modoverrides_and_comments():
    source = b'''-- generated by DST
    return {
      ["workshop-378160973"] = {
        enabled = true,
        configuration_options = { SHOWPLAYERICONS = true, amount = 3, mode = "friends" },
      },
      --[=[ An optional second mod. ]=]
      ['workshop-123456789'] = {enabled = false; configuration_options = {};},
    }; -- trailing comment
    '''
    assert read_mods(source) == [
        {"id": "123456789", "enabled": False, "options": {}},
        {"id": "378160973", "enabled": True,
         "options": {"SHOWPLAYERICONS": True, "amount": 3, "mode": "friends"}},
    ]


def test_generated_settings_roundtrip_including_utf8_and_arrays():
    options = {"中文": 'a "quote" and \\ newline\n饥荒', "nested": {"list": [True, False, 2]},
               "inert": 'os.execute("not executed")'}
    text = "return " + lua({"workshop-378160973": {"enabled": True, "configuration_options": options}})
    assert read_mods(text.encode())[0]["options"] == options


def test_long_strings_numbers_and_nil_fields():
    data = b'''return { ["workshop-378160973"] = {enabled=true,
      configuration_options = {message=[=[\nhello "friends"]=], number=-1.5e2,
        bits=0xFF, removed=nil, array={[1]="a", [2]="b"}}}}'''
    assert read_mods(data)[0]["options"] == {
        "message": 'hello "friends"', "number": -150, "bits": 255, "array": ["a", "b"]}


@pytest.mark.parametrize("text", [
    'return os.execute("evil")', 'local x = {}; return x',
    'return {["workshop-378160973"]={enabled=true,configuration_options={x=1+1}}}',
    'return {}; os.execute("evil")',
    'return {["workshop-378160973"]={enabled=function() end}}',
    'return {["workshop-378160973"]={enabled=true,enabled=false}}',
    'return {["workshop-378160973"]={enabled=true,configuration_options={x=1e999}}}',
    'return {["workshop-378160973"]={enabled=true,configuration_options={x="\\999"}}}',
    'return {["local-file-mod"]={enabled=true}}',
    'return {["workshop-378160973"]={enabled="yes"}}',
    'return {["workshop-378160973"]={enabled=true,configuration_options={x={[3]="hole"}}}}',
    'return {', '--unterminated [ignored]\nreturn { ["key"]=',
])
def test_expressions_malformed_or_unsupported_settings_rejected(text):
    with pytest.raises(PanelError):
        read_mods(text.encode())


def test_oversized_mod_file_rejected():
    with pytest.raises(PanelError, match="128 KiB"):
        read_mods(b" " * (128 * 1024 + 1))


def test_bom_empty_mod_list():
    assert read_mods(b"\xef\xbb\xbfreturn {}") == []
